// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// binary_BUDS_cpp
Rcpp::List binary_BUDS_cpp(double alpha, double power, double p0, double p1, int n_lb, int n_ub, double p0L, double p0U, int pgrid_points, Rcpp::StringVector robust_objective, Rcpp::String robust_ref, double robust_max_inflation, int robust_N_cap, bool robust_auto_expand, double robust_expand_step, double robust_expand_max);
RcppExport SEXP _BUDS_binary_BUDS_cpp(SEXP alphaSEXP, SEXP powerSEXP, SEXP p0SEXP, SEXP p1SEXP, SEXP n_lbSEXP, SEXP n_ubSEXP, SEXP p0LSEXP, SEXP p0USEXP, SEXP pgrid_pointsSEXP, SEXP robust_objectiveSEXP, SEXP robust_refSEXP, SEXP robust_max_inflationSEXP, SEXP robust_N_capSEXP, SEXP robust_auto_expandSEXP, SEXP robust_expand_stepSEXP, SEXP robust_expand_maxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type power(powerSEXP);
    Rcpp::traits::input_parameter< double >::type p0(p0SEXP);
    Rcpp::traits::input_parameter< double >::type p1(p1SEXP);
    Rcpp::traits::input_parameter< int >::type n_lb(n_lbSEXP);
    Rcpp::traits::input_parameter< int >::type n_ub(n_ubSEXP);
    Rcpp::traits::input_parameter< double >::type p0L(p0LSEXP);
    Rcpp::traits::input_parameter< double >::type p0U(p0USEXP);
    Rcpp::traits::input_parameter< int >::type pgrid_points(pgrid_pointsSEXP);
    Rcpp::traits::input_parameter< Rcpp::StringVector >::type robust_objective(robust_objectiveSEXP);
    Rcpp::traits::input_parameter< Rcpp::String >::type robust_ref(robust_refSEXP);
    Rcpp::traits::input_parameter< double >::type robust_max_inflation(robust_max_inflationSEXP);
    Rcpp::traits::input_parameter< int >::type robust_N_cap(robust_N_capSEXP);
    Rcpp::traits::input_parameter< bool >::type robust_auto_expand(robust_auto_expandSEXP);
    Rcpp::traits::input_parameter< double >::type robust_expand_step(robust_expand_stepSEXP);
    Rcpp::traits::input_parameter< double >::type robust_expand_max(robust_expand_maxSEXP);
    rcpp_result_gen = Rcpp::wrap(binary_BUDS_cpp(alpha, power, p0, p1, n_lb, n_ub, p0L, p0U, pgrid_points, robust_objective, robust_ref, robust_max_inflation, robust_N_cap, robust_auto_expand, robust_expand_step, robust_expand_max));
    return rcpp_result_gen;
END_RCPP
}
// tte_grid_search_cpp
List tte_grid_search_cpp(double hz0, double hz1, double hr, double x0, double alpha, double beta, double rate, int nsingle, double tasingle, double ceps, double alphaeps, int nbmaxiter, bool verbose);
RcppExport SEXP _BUDS_tte_grid_search_cpp(SEXP hz0SEXP, SEXP hz1SEXP, SEXP hrSEXP, SEXP x0SEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP rateSEXP, SEXP nsingleSEXP, SEXP tasingleSEXP, SEXP cepsSEXP, SEXP alphaepsSEXP, SEXP nbmaxiterSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type hz0(hz0SEXP);
    Rcpp::traits::input_parameter< double >::type hz1(hz1SEXP);
    Rcpp::traits::input_parameter< double >::type hr(hrSEXP);
    Rcpp::traits::input_parameter< double >::type x0(x0SEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type rate(rateSEXP);
    Rcpp::traits::input_parameter< int >::type nsingle(nsingleSEXP);
    Rcpp::traits::input_parameter< double >::type tasingle(tasingleSEXP);
    Rcpp::traits::input_parameter< double >::type ceps(cepsSEXP);
    Rcpp::traits::input_parameter< double >::type alphaeps(alphaepsSEXP);
    Rcpp::traits::input_parameter< int >::type nbmaxiter(nbmaxiterSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(tte_grid_search_cpp(hz0, hz1, hr, x0, alpha, beta, rate, nsingle, tasingle, ceps, alphaeps, nbmaxiter, verbose));
    return rcpp_result_gen;
END_RCPP
}
// tte_BUDS_search_cpp
List tte_BUDS_search_cpp(double p0L, double p0U, double p1, double x0, double rate, double alpha, double beta, int n_design_points, int n_eval_grid, int nsim_eval, int n_ub, double ceps, double alphaeps, int nbmaxiter, Rcpp::StringVector BUDS_objective, Rcpp::String regret_basis, bool verbose);
RcppExport SEXP _BUDS_tte_BUDS_search_cpp(SEXP p0LSEXP, SEXP p0USEXP, SEXP p1SEXP, SEXP x0SEXP, SEXP rateSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP n_design_pointsSEXP, SEXP n_eval_gridSEXP, SEXP nsim_evalSEXP, SEXP n_ubSEXP, SEXP cepsSEXP, SEXP alphaepsSEXP, SEXP nbmaxiterSEXP, SEXP BUDS_objectiveSEXP, SEXP regret_basisSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type p0L(p0LSEXP);
    Rcpp::traits::input_parameter< double >::type p0U(p0USEXP);
    Rcpp::traits::input_parameter< double >::type p1(p1SEXP);
    Rcpp::traits::input_parameter< double >::type x0(x0SEXP);
    Rcpp::traits::input_parameter< double >::type rate(rateSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< int >::type n_design_points(n_design_pointsSEXP);
    Rcpp::traits::input_parameter< int >::type n_eval_grid(n_eval_gridSEXP);
    Rcpp::traits::input_parameter< int >::type nsim_eval(nsim_evalSEXP);
    Rcpp::traits::input_parameter< int >::type n_ub(n_ubSEXP);
    Rcpp::traits::input_parameter< double >::type ceps(cepsSEXP);
    Rcpp::traits::input_parameter< double >::type alphaeps(alphaepsSEXP);
    Rcpp::traits::input_parameter< int >::type nbmaxiter(nbmaxiterSEXP);
    Rcpp::traits::input_parameter< Rcpp::StringVector >::type BUDS_objective(BUDS_objectiveSEXP);
    Rcpp::traits::input_parameter< Rcpp::String >::type regret_basis(regret_basisSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(tte_BUDS_search_cpp(p0L, p0U, p1, x0, rate, alpha, beta, n_design_points, n_eval_grid, nsim_eval, n_ub, ceps, alphaeps, nbmaxiter, BUDS_objective, regret_basis, verbose));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BUDS_binary_BUDS_cpp", (DL_FUNC) &_BUDS_binary_BUDS_cpp, 16},
    {"_BUDS_tte_grid_search_cpp", (DL_FUNC) &_BUDS_tte_grid_search_cpp, 13},
    {"_BUDS_tte_BUDS_search_cpp", (DL_FUNC) &_BUDS_tte_BUDS_search_cpp, 17},
    {NULL, NULL, 0}
};

RcppExport void R_init_BUDS(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
