# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

binary_BUDS_cpp <- function(alpha, power, p0, p1, n_lb, n_ub, p0L, p0U, pgrid_points, robust_objective, robust_ref, robust_max_inflation, robust_N_cap, robust_auto_expand, robust_expand_step, robust_expand_max) {
    .Call(`_BUDS_binary_BUDS_cpp`, alpha, power, p0, p1, n_lb, n_ub, p0L, p0U, pgrid_points, robust_objective, robust_ref, robust_max_inflation, robust_N_cap, robust_auto_expand, robust_expand_step, robust_expand_max)
}

tte_grid_search_cpp <- function(hz0, hz1, hr, x0, alpha, beta, rate, nsingle, tasingle, ceps, alphaeps, nbmaxiter, verbose) {
    .Call(`_BUDS_tte_grid_search_cpp`, hz0, hz1, hr, x0, alpha, beta, rate, nsingle, tasingle, ceps, alphaeps, nbmaxiter, verbose)
}

tte_BUDS_search_cpp <- function(p0L, p0U, p1, x0, rate, alpha, beta, n_design_points, n_eval_grid, nsim_eval, n_ub, ceps, alphaeps, nbmaxiter, BUDS_objective, regret_basis, verbose) {
    .Call(`_BUDS_tte_BUDS_search_cpp`, p0L, p0U, p1, x0, rate, alpha, beta, n_design_points, n_eval_grid, nsim_eval, n_ub, ceps, alphaeps, nbmaxiter, BUDS_objective, regret_basis, verbose)
}

